[tool]
  [tool.bumpversion]
    allow_dirty = true
    current_version = "0.8.1"

    [[tool.bumpversion.files]]
      filename = "script.py"
      replace = "__version__ = \"{new_version}\""
      search = "__version__ = \"{current_version}\""
